baseURL = "https://staging-rovu.netlify.app"
languageCode = "en-us"
title = "RO.VU"
theme = "PaperMod"
# enables adding date even if no date is set manually based on git commits
enableGitInfo = true
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "JRO"
    description = "Notes and info"
    githubUsername = "#"
    accent = "#47536e"
    showBorder = false
    backgroundColor = "#fff"
    font = "Noto Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "java"]

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2


[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/passions/"
    name = "Passions"
    weight = 4

    
[[menu.main]]
    url = "/dash/"    
    name = "JRO Dashboard"
    weight = 5
    
# "Disable" pagination
# TODO: Disable pagination in template
paginate = 99

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:j@ro.vu"
    name = "envelope-o"
    weight = 1


#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4


